### ISSUE TITLE
getting NotImplementedError

### ISSUE THREAD

**Issue by Sivaneni** [ollama/ollama-python#160]
Task exception was never retrieved
future: <Task finished name='Task-160' coro=<Connection.run() done, defined at D:\anaconda3\envs\myenv\Lib\site-packages\playwright\_impl\_connection.py:265> exception=NotImplementedError()>
Traceback (most recent call last):
  File "D:\anaconda3\envs\myenv\Lib\site-packages\playwright\_impl\_connection.py", line 272, in run
    await self._transport.connect()
  File "D:\anaconda3\envs\myenv\Lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "D:\anaconda3\envs\myenv\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\asyncio\subprocess.py", line 223, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\asyncio\base_events.py", line 1708, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\asyncio\base_events.py", line 503, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2024-05-20 18:55:58.250 Uncaught app exception
Traceback (most recent call last):
  File "D:\anaconda3\envs\myenv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Welcome\OneDrive\Desktop\Generative AI\awesome-llm-apps\web_scrapping_ai_agent\ai_scrapper.py", line 37, in <module>   
    result = smart_scraper_graph.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\site-packages\scrapegraphai\graphs\smart_scraper_graph.py", line 112, in run
    self.final_state, self.execution_info = self.graph.execute(inputs)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\site-packages\scrapegraphai\graphs\base_graph.py", line 107, in execute
    result = current_node.execute(state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\site-packages\scrapegraphai\nodes\fetch_node.py", line 155, in execute
    document = loader.load()
               ^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\site-packages\langchain_core\document_loaders\base.py", line 29, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\site-packages\scrapegraphai\docloaders\chromium.py", line 103, in lazy_load
    html_content = asyncio.run(scraping_fn(url))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\site-packages\scrapegraphai\docloaders\chromium.py", line 75, in ascrape_playwright
    async with async_playwright() as p:
  File "D:\anaconda3\envs\myenv\Lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\asyncio\subprocess.py", line 223, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\asyncio\base_events.py", line 1708, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\myenv\Lib\asyncio\base_events.py", line 503, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by mxyng** [comment]
That exception looks like it was raised by playwright and unrelated to ollama-python. You'll get better help by creating an issue in their repo
