### ISSUE TITLE
ollama._types.ResponseError: llama runner process no longer running: -1 

### ISSUE THREAD

**Issue by WangRongsheng** [ollama/ollama-python#269]
```
Traceback (most recent call last):
  File "/wrs/ollama_qwen.py", line 15, in <module>
    response = client.chat(model='qwen2:1.5b', messages=[
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/ollama/_client.py", line 236, in chat
    return self._request_stream(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/ollama/_client.py", line 99, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/ollama/_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: llama runner process no longer running: -1 
```

**Comment by msskaa12** [comment]
same problem ,  how do you fix it , bro @WangRongsheng
